version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 178aj900
      POSTGRES_DB: LandBike
    volumes:
      # - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
      # - ./postgresql/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres_data:
