version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 178aj900
      POSTGRES_DB: LandBike
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
      # - ./postgresql/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_container
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:178aj900@postgres/LandBike
    restart: always


  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: frontend_container
    volumes:
      - ./Frontend:/app/frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@admin.com'
      PGADMIN_DEFAULT_PASSWORD: 'root'
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: always

volumes:
  postgres_data:
